### ISSUE TITLE
not able to get token/do anything

### ISSUE THREAD

**Issue by ianseyer** [Cindicator/CindicatorArbitrageBot#1]
your bot seems to be down

**Comment by korcky** [comment]
If you mean bot that currently working in telegram, then add screenshots and more description.
Or you clone this code and trying to run in?

**Comment by korcky** [comment]
Friendly ping

**Comment by korcky** [comment]
Hope that everything works fine. Closed due to inactivity. Feel free to open it if something go wrong.

**Comment by ianseyer** [comment]
Sorry for the delay.

"To start the bot working, a user must register on www.cindicator.com/arbitrage-bot by entering their email address. "

That link takes you to your medium page, i.e. impossible to get a token.

**Comment by korcky** [comment]
Try [this](https://cindicator.com/arbitrage-bot) link, should work.

**Comment by ianseyer** [comment]
Yup! Thanks.
