### ISSUE TITLE
wallet

### ISSUE THREAD

**Issue by nonacosa** [Cindicator/CindicatorArbitrageBot#2]

**Comment by nonacosa** [comment]
![image](https://user-images.githubusercontent.com/14212375/31960982-0f61d2e2-b8bf-11e7-95ba-5a21335e08cf.png)
i get it at here... it is so small ! but i want to know ：Whether he supports 'imToken' this ETH app ?

**Comment by korcky** [comment]
Firstly, this repository only about CindicatorArbitrageBot. In future, you can ask  questions like this in our [telegram channel](https://t.me/cindicator_chat).
Secondly, our token implements [ERC-20 standard](https://theethereum.wiki/w/index.php/ERC20_Token_Standard) and you should use ERC-20 compatible wallets (like Metamask, Parity, Mist, MyEtherWallet.com, we have instructions for them) to work with our token.
You may try to find how to add ERC-20 tokens into imToken, google helps you.

**Comment by korcky** [comment]
Offtopic issue.
